# Generated by Django 5.0.13 on 2025-03-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0003_alter_votante_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='localidad',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10),
        ),
    ]
