# Generated by Django 5.0.13 on 2025-03-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0004_alter_candidato_localidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
