# Generated by Django 5.0.13 on 2025-03-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0006_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votaciones.candidato')),
                ('votante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='votaciones.votante')),
            ],
        ),
    ]
