# Generated by Django 5.0.13 on 2025-03-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0007_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería')], max_length=20),
        ),
    ]
