# Generated by Django 5.0.13 on 2025-03-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0008_alter_votante_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='fecha',
        ),
    ]
