# Generated by Django 5.0.13 on 2025-03-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0009_remove_voto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='dni_votante',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='voto',
            name='votante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votaciones.votante'),
        ),
    ]
